services:
  - type: web
    name: no2-prediction-system
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app_deploy:app --timeout 300 --workers 1
    envVars:
      - key: PYTHON_VERSION
        value: 3.8.10
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
    healthCheckPath: /